### ISSUE TITLE
Can Choice construction be constexpr?

### ISSUE THREAD

**Issue by danakj** [chromium/subspace#138]
When the value being constructed in the choice is trivially-default-constructible, its lifetime can begin by being assigned to (11.5.6.1 of [C++20 spec](https://isocpp.org/files/papers/N4860.pdf)).

So we can provide a constexpr path in this case for `Choice<...>::with<X>(y)`?

Then we can also do the same for `Choice<...>::set<X>(y)`?

**Comment by ANUSHRAV01** [comment]
@danakj I am trying to figure out myself about this. But I like to help as much as i can :-

Yes, you are correct that if the value being constructed in the choice is trivially-default-constructible, its lifetime can begin by being assigned to (as specified in 11.5.6.1 of the C++20 spec).

As a result, in such cases, it would be possible to provide a constexpr path for Choice<...>::with<X>(y) and Choice<...>::set<X>(y).

**Comment by ANUSHRAV01** [comment]
@danakj This is a code snippet which might help you with what u are trying to do
template<typename T, typename... Ts>
struct Choice {
    // ...

    template<typename X>
    static constexpr Choice<T, Ts...> with(X y) {
        if constexpr (std::is_same_v<T, X>) {
            return Choice<T, Ts...>{true, y};
        } else {
            return Choice<Ts...>::template with<X>(y);
        }
    }

    // ...
};

**Comment by ANUSHRAV01** [comment]
In this example, we use if constexpr to conditionally return a Choice object with the value y assigned to it, depending on whether X is the same type as T. This approach allows us to create a constexpr path for Choice<...>::with<X>(y) when y is trivially-default-constructible.

A similar approach could be used for Choice<...>::set<X>(y), with the main difference being that set<X>(y) modifies an existing Choice object rather than creating a new one.

Note that in both cases, it is important to ensure that y is indeed trivially-default-constructible in order for these constexpr paths to be valid.



@danakj If u find this useful. Kindly inform me as this motivates me to contribute more to open-source and help community to grow more. And if i can help more just reach out

**Comment by danakj** [comment]
`std::construct_at()` allows changing the active union member in a constexpr context without it being trivially default constructible, as a drop-in replacement for placement-new. With that, all of Choice can become constexpr.
